In [1]:
import pandas as pd

In [3]:
import os

print(os.getcwd())

c:\Users\jithe\OneDrive\Desktop\Internship\bluestock_mf_capstone\notebooks

In [6]:
from pathlib import Path
exel_dir=Path("../data/raw")
for file in exel_dir.glob("*.xlsx"):
    df=pd.read_excel(file)
    csv_name=file.with_suffix(".csv")
    df.to_csv(csv_name,index=False)
    print(f"Converted: {file.name} -> {csv_name.name}")

Converted: 01_fund_master.xlsx -> 01_fund_master.csv
Converted: 02_nav_history.xlsx -> 02_nav_history.csv
Converted: 03_aum_by_fund_house.xlsx -> 03_aum_by_fund_house.csv
Converted: 04_monthly_sip_inflows.xlsx -> 04_monthly_sip_inflows.csv
Converted: 05_category_inflows.xlsx -> 05_category_inflows.csv
Converted: 06_industry_folio_count.xlsx -> 06_industry_folio_count.csv
Converted: 07_scheme_performance.xlsx -> 07_scheme_performance.csv
Converted: 08_investor_transactions.xlsx -> 08_investor_transactions.csv
Converted: 09_portfolio_holdings.xlsx -> 09_portfolio_holdings.csv
Converted: 10_benchmark_indices.xlsx -> 10_benchmark_indices.csv

In [9]:
import logging
from IPython.display import display

logging.basicConfig(level=logging.INFO,
                    format="%(levelname)s | %(message)s")

log = logging.getLogger(__name__)

BASE_DIR = Path.cwd().parent
RAW_DIR = BASE_DIR / "data" / "raw"

csv_files = sorted(RAW_DIR.glob("*.csv"))

if not csv_files:
    log.error(f"No CSV files found in {RAW_DIR}")

else:
    log.info(f"Found {len(csv_files)} CSV files")

    for file in csv_files:
        try:
            df = pd.read_csv(file)

            print("\n" + "="*60)
            print(f"File Name : {file.name}")
            print(f"Shape     : {df.shape}")

            print("\nDtypes:")
            print(df.dtypes)

            print("\nHead:")
            display(df.head())

        except Exception as e:
            log.error(f"Failed to load {file.name}: {e}")

INFO | Found 10 CSV files

============================================================
File Name : 01_fund_master.csv
Shape     : (40, 15)

Dtypes:
amfi_code               int64
fund_house             object
scheme_name            object
category               object
sub_category           object
plan                   object
launch_date            object
benchmark              object
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager           object
risk_category          object
sebi_category_code     object
dtype: object

Head:

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

============================================================
File Name : 02_nav_history.csv
Shape     : (46000, 3)

Dtypes:
amfi_code      int64
date          object
nav          float64
dtype: object

Head:

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

============================================================
File Name : 03_aum_by_fund_house.csv
Shape     : (90, 5)

Dtypes:
date               object
fund_house         object
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

Head:

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

============================================================
File Name : 04_monthly_sip_inflows.csv
Shape     : (48, 6)

Dtypes:
month                         object
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

Head:

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01-01,11517,4.91,9.10,4.80,NaN
1,2022-02-01,11438,4.93,8.20,4.85,NaN
2,2022-03-01,12328,5.09,10.50,5.01,NaN
3,2022-04-01,11863,5.48,9.52,5.12,NaN
4,2022-05-01,12286,5.55,8.10,5.15,NaN

============================================================
File Name : 05_category_inflows.csv
Shape     : (144, 3)

Dtypes:
month               object
category            object
net_inflow_crore     int64
dtype: object

Head:

        month         category  net_inflow_crore
0  2024-04-01        Large Cap              2413
1  2024-04-01          Mid Cap              3897
2  2024-04-01        Small Cap              3533
3  2024-04-01        Flexi Cap              4947
4  2024-04-01  Large & Mid Cap              4214

============================================================
File Name : 06_industry_folio_count.csv
Shape     : (21, 6)

Dtypes:
month                   object
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

Head:

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01-01,13.26,9.28,1.86,0.80,1.33
1,2022-04-01,13.91,9.74,1.95,0.83,1.39
2,2022-07-01,13.85,9.69,1.94,0.83,1.38
3,2022-10-01,14.12,9.88,1.98,0.85,1.41
4,2023-01-01,14.81,10.37,2.07,0.89,1.48

============================================================
File Name : 07_scheme_performance.csv
Shape     : (40, 19)

Dtypes:
amfi_code               int64
scheme_name            object
fund_house             object
category               object
plan                   object
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade             object
dtype: object

Head:

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

============================================================
File Name : 08_investor_transactions.csv
Shape     : (32778, 13)

Dtypes:
investor_id            object
transaction_date       object
amfi_code               int64
transaction_type       object
amount_inr              int64
state                  object
city                   object
city_tier              object
age_group              object
gender                 object
annual_income_lakh    float64
payment_mode           object
kyc_status             object
dtype: object

Head:

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

============================================================
File Name : 09_portfolio_holdings.csv
Shape     : (322, 8)

Dtypes:
amfi_code              int64
stock_symbol          object
stock_name            object
sector                object
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date        object
dtype: object

Head:

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

============================================================
File Name : 10_benchmark_indices.csv
Shape     : (8050, 3)

Dtypes:
date            object
index_name      object
close_value    float64
dtype: object

Head:

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

#Day 1 - Task 6

In [16]:
from pathlib import Path
import pandas as pd

DATA_DIR=Path().resolve().parent
RAW_DIR= DATA_DIR / "data" / "raw"

In [17]:
df=pd.read_csv(RAW_DIR/"01_fund_master.csv")
print(df.shape)
df.head()

(40, 15)

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [18]:
print(f"Fund Houses: {df['fund_house'].unique()}")

Fund Houses: ['SBI Mutual Fund' 'HDFC Mutual Fund' 'ICICI Prudential MF'
 'Nippon India MF' 'Kotak Mahindra MF' 'Axis Mutual Fund'
 'Aditya Birla Sun Life MF' 'UTI Mutual Fund' 'Mirae Asset MF'
 'DSP Mutual Fund']

In [19]:
print(f"Categories: {df['category'].unique()}")

Categories: ['Equity' 'Debt']

In [20]:
print(f"Sub-Categories: {df['sub_category'].unique()}")

Sub-Categories: ['Large Cap' 'Small Cap' 'Gilt' 'Mid Cap' 'Short Duration' 'Value'
 'Liquid' 'Index/ETF' 'Flexi Cap' 'Index' 'Large & Mid Cap' 'ELSS']

In [22]:
print(f"Risk Grades: {df['risk_category'].unique()}")

Risk Grades: ['Moderate' 'Very High' 'Low' 'High' 'Moderately High']

In [23]:
fund_master=pd.read_csv(RAW_DIR / "01_fund_master.csv")
nav_history=pd.read_csv(RAW_DIR / "02_nav_history.csv")

In [25]:
print(fund_master.columns)
print(nav_history.columns)

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='object')
Index(['amfi_code', 'date', 'nav'], dtype='object')

In [26]:
missing = fund_master[~fund_master['amfi_code'].isin(nav_history['amfi_code'])]

print(f"Total funds in master : {len(fund_master)}")
print(f"Total in nav history  : {len(nav_history)}")
print(f"Missing codes         : {len(missing)}")
print(missing)

Total funds in master : 40
Total in nav history  : 46000
Missing codes         : 0
Empty DataFrame
Columns: [amfi_code, fund_house, scheme_name, category, sub_category, plan, launch_date, benchmark, expense_ratio_pct, exit_load_pct, min_sip_amount, min_lumpsum_amount, fund_manager, risk_category, sebi_category_code]
Index: []

In [27]:
REPORTS_DIR = BASE_DIR / "reports"
REPORTS_DIR.mkdir(exist_ok=True)

missing.to_csv(REPORTS_DIR / "data_quality_report.txt", index=False)
print("Report saved!")

Report saved!